services:
  traceview:
    # Build the production image from the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ardoco/traceview:latest
    container_name: traceview
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

