name: Docker Push

on:
  workflow_dispatch:
#  push:
#    # Publish `main` as Docker `latest` image.
#    branches:
#      - main
#    paths-ignore:
#      - '**.md'
#      - '.github/**'

    # Publish `v1.2.3` tags as releases.
#    tags:
#      - v*

jobs:
  push:
    uses: ardoco/actions/.github/workflows/docker.yml@main
    with:
      image-name: traceview
      push: true